<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Capturing screenshot]]>
    </line>
    <line>
      <![CDATA[login successfully executed]]>
    </line>
    <line>
      <![CDATA[Test case passed for you]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Basics" duration-ms="805" started-at="2020-12-12T15:11:53 IST" finished-at="2020-12-12T15:11:54 IST">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="250" started-at="2020-12-12T15:11:53 IST" finished-at="2020-12-12T15:11:53 IST">
      <class name="com.w2a.testcases.BankManagerLoginTest">
        <test-method status="FAIL" signature="loginAsBankManager()[pri:0, instance:com.w2a.testcases.BankManagerLoginTest@2f54a33d]" name="loginAsBankManager" duration-ms="223" started-at="2020-12-12T15:11:53 IST" finished-at="2020-12-12T15:11:53 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[login not successfull]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: login not successfull
at org.testng.Assert.fail(Assert.java:99)
at com.w2a.testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Capturing screenshot]]>
            </line>
            <line>
              <![CDATA[login successfully executed]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.w2a.testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="540" started-at="2020-12-12T15:11:53 IST" finished-at="2020-12-12T15:11:54 IST">
      <class name="com.w2a.testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.w2a.testcases.AddCustomerTest@61d6015a]" name="setUp" is-config="true" duration-ms="9004" started-at="2020-12-12T15:11:44 IST" finished-at="2020-12-12T15:11:53 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.testcases.AddCustomerTest@61d6015a]" name="addCustomer" duration-ms="527" started-at="2020-12-12T15:11:53 IST" data-provider="getData" finished-at="2020-12-12T15:11:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[bala]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[singh]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[23rw]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test case passed for you]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.w2a.testcases.AddCustomerTest@61d6015a]" name="tearDown" is-config="true" duration-ms="632" started-at="2020-12-12T15:11:54 IST" finished-at="2020-12-12T15:11:54 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.w2a.testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
